### ISSUE TITLE
data type control while reading transfers_ft

### ISSUE THREAD

**Issue by bhargavasana** [MetropolitanTransportationCommission/fast-trips#10]
Something similar to what is being done while reading stops_ft is need for transfers_ft too:

comment:Read the fast-trips supplemental stops data file. Make sure stop ID is read as a string.
        stops_ft_df = pandas.read_csv(os.path.join(input_dir, Stop.INPUT_STOPS_FILE),
                                      dtype={Stop.STOPS_COLUMN_STOP_ID:object})

Otherwise, the from and to stop ids are being read in as numbers which is creating a problem downstream when stop_id_num needs to be merged in.

**Comment by lmz** [comment]
Thx for fixing, this is now in both the develop and hyperpath_tree branches.
https://github.com/MetropolitanTransportationCommission/fast-trips/commit/555a90d111af1d8ec8f6bf8256c1243a64dee1ae
