### ISSUE TITLE
Figure out a more sophisticated "chunking size"

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#32]
[Initial crack at chunking](https://github.com/MetropolitanTransportationCommission/fast-trips/commit/329ce7c488d2f65b8f6e2a4124f8cef18c24df72) from @lmz just chunks to 1,000 trips in order to avoid memory overflows from the segment-based overlap variable calculation.

**Comment by lmz** [comment]
It's now configurable via the config param 'overlap_chunk_size'
