### ISSUE TITLE
Clarify how to run fast-trips in ReadMe.md

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#42]
ReadMe / Quick Start needs an example of what you actually write when you run Fast-Trips.

- What are various config options? 
- What are required inputs and in what order to you specify them?

runtest should probably also be renamed to runXXX where XXX implies an actual fast-trips run.

**Comment by lmz** [comment]
FYI I always run from command line so I resurrected runTest.py as runFastTrips.py: https://github.com/MetropolitanTransportationCommission/fast-trips/blob/develop/scripts/runFastTrips.py

**Comment by e-lo** [comment]
@lmz : if you are going to run from command line, please make sure it is logging the parameters you pass it somewhere ;-)

**Comment by lmz** [comment]
I think everything is in the ft_output_config.txt except for the pathweights and input config files themselves, which I could add.

**Comment by e-lo** [comment]
These commits break running it from run_fasttrips.py: see my comments 
https://github.com/MetropolitanTransportationCommission/fast-trips/commit/92d71c39c4b54e4bede4ae02c35e02011561dbf7

**Comment by e-lo** [comment]
[ and now you can use the tests! ;-) ]

**Comment by lmz** [comment]
How are you running the tests?

**Comment by lmz** [comment]
oh nm - i see. running "pytest"

**Comment by lmz** [comment]
Will fix tests.  Sorry, I knew renaming to input_network_dir would break them and forgot to fix, but that's what it was originally called and I thought the abbreviation unnecessary :open_mouth:

**Comment by e-lo** [comment]
AHA - OMG I have been trying to figure out what was going on but duh... `net` --> `network` .  Glad one of us [ you ] can read.  The error [`TypeError: run_setup() takes at least 6 arguments (7 given)`]
was non-obvious [to me]

**Comment by lmz** [comment]
:+1: yea, I think that's all it was, the tests run fine for me now

**Comment by e-lo** [comment]
@lmz  : please add command used for running the test scenario

https://github.com/MetropolitanTransportationCommission/fast-trips/tree/develop#running-fast-trips

**Comment by e-lo** [comment]
i added this.
