### ISSUE TITLE
Clean whitespace from from files when reading in CSVs

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#53]
Very easy to inadvertently have extra whitespace before commas....let's just clean it to avoid the error

**Comment by lmz** [comment]
I can easily use pandas option skipinitialspace=True but it won't deal with trailing spaces.
Are you talking about the pathweight file or something else?

**Comment by e-lo** [comment]
What about [`Series.str.strip()`](http://stackoverflow.com/questions/33788913/pythonic-efficient-way-to-strip-whitespace-from-every-pandas-data-frame-cell-tha) ?

**Comment by e-lo** [comment]
All files, actually.  In some of the PSRC processes there are random whitespaces being generated.  In an ideal world they wouldn't be there, but we also don't want Fast-Trips to be overly fragile to them.

**Comment by e-lo** [comment]
Example:

> from_stop_id,to_stop_id,dist,from_route_id,to_route_id,schedule_precedence
>65545,65588,0.22, , , 
>65588,65545,0.22, , , 
>65545,66021,0.3, , ,

**Comment by lmz** [comment]
skipinitialspace=True should take care of that example
Adding in the strip is doable but I'd need to loop through all the columns in all the places they're read.  Also if they're numerical columns then there'd need to be casting.

**Comment by e-lo** [comment]
This works for now. Will reopen if need be.
