### ISSUE TITLE
where should I put the tutorial?

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#58]
Right now I stripped it out of Fast-Trips directory locally and have it in a self-contained folder with:

 - examples  
 - helper scripts for visualizing on maps  
 - ipython notebook that goes through the input verification, running fast-trips, and displaying results.

I could either put it into the fast-trips examples OR create a new repo designed as a tutorial.

If the latter [ which is cleaner ], then what "organization" would you like me to put the repo under?

**Comment by e-lo** [comment]
It is here for now: https://github.com/e-lo/fast-trips-tutorial

**Comment by lmz** [comment]
I would put it into the Examples folder

**Comment by e-lo** [comment]
Moved to https://github.com/Fast-Trips/fast-trips-tutorial
