### ISSUE TITLE
Start and end times formatting in fare_rules_ft.txt

### ISSUE THREAD

**Issue by bhargavasana** [MetropolitanTransportationCommission/fast-trips#6]
If start_time and end_time in fare_rules_ft.txt are blank, there is an exception thrown. We either could  handle blanks or enforce that 00:00:00, 23:59:59.

**Comment by e-lo** [comment]
Per https://github.com/osplanning-data-standards/GTFS-PLUS/commit/ac9303b2dc7e46dc9d7ba01aeac3af6525183482

**Comment by lmz** [comment]
Thanks to @bhargavasana for fixing, this is in the develop and hyperpath_tree branches.
https://github.com/MetropolitanTransportationCommission/fast-trips/commit/555a90d111af1d8ec8f6bf8256c1243a64dee1ae
