### ISSUE TITLE
vehicles_ft fields are "optional"

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#65]
But for vehicle name.
Explicitly say what default was used if none provided.

**Comment by lmz** [comment]
What should defaults be if non provided for accel, decel and max speed?
I'm looking at TQSM I see in Exhibit 6-2 (on page 6-4) accel rates but by vehicle type and for two different speeds.  Page 6-3 lists "typical values" of 25 mi/h max speed.

I could use 3.4 ft/s^2 accel, 4.0 decel ft/s^2 decel and 50 mi/h (or 20 mi/h bus) but that seems pretty crappy for rail?

**Comment by e-lo** [comment]
https://www.sacrt.com/lightrail.stm has some values that we could use for rail?

**Comment by lmz** [comment]
I think it's more straightforward to not alter the travel time if these aren't specified, which is what we originally decided when this was implemented. The vehicles_ft file doesn't have a mode, so to do mode-specific defaults, we'd have to rely on how it joins to trips (which specify modes) and routes (which specify vehicle types) which gets confusing fast.

**Comment by e-lo** [comment]
I think I'm okay with this.  We will need to document it somewhere [ thinking on this ]
Are we good to go with all of the fields being optional now?

**Comment by lmz** [comment]
I think so. I tested blanking fields and removing the columns.
