### ISSUE TITLE
transfers_ft.txt is assumed to be a required file

### ISSUE THREAD

**Issue by bhargavasana** [MetropolitanTransportationCommission/fast-trips#7]
The GTFS-PLUS standards say that transfers_ft.txt is optional. However, fast-trips code is assuming it to be always present.

**Comment by e-lo** [comment]
Per: https://github.com/osplanning-data-standards/GTFS-PLUS/commit/ac9303b2dc7e46dc9d7ba01aeac3af6525183482

**Comment by lmz** [comment]
Given that the spec now says it's required, is this still an issue for fast-trips?

**Comment by bhargavasana** [comment]
This is no longer an issue since spec has changed.
