### ISSUE TITLE
Fix data type in fare_rules_ft to allow "default" or "blank" for start_time end_time

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#8]

**Comment by e-lo** [comment]
Per https://github.com/osplanning-data-standards/GTFS-PLUS/commit/ac9303b2dc7e46dc9d7ba01aeac3af6525183482

**Comment by lmz** [comment]
https://github.com/MetropolitanTransportationCommission/fast-trips/commit/555a90d111af1d8ec8f6bf8256c1243a64dee1ae
