### ISSUE TITLE
CPP extension not returning trace

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#82]
[ft_debug.txt](https://github.com/MetropolitanTransportationCommission/fast-trips/files/1137238/ft_debug.txt)
[ft_output_config.txt](https://github.com/MetropolitanTransportationCommission/fast-trips/files/1137239/ft_output_config.txt)

> 017-07-10 12:45:47 [ERROR/MainProcess]   File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Assignment.py", line 1016, in find_trip_based_pathset
>     1 if trace else 0)
> 
> 2017-07-10 12:45:47 [ERROR/MainProcess] ValueError: need more than 12 values to unpack
> 
> ('Unexpected error:', <type 'exceptions.ValueError'>)
> 2017-07-10 12:45:47 [CRITICAL/MainProcess] Unexpected error: <type 'exceptions.ValueError'>
> Traceback (most recent call last):
>   File "run_trace.py", line 25, in <module>
>     time_window      = 30)
>   File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Run.py", line 203, in run_fasttrips
>     r = ft.run_assignment(fasttrips.Assignment.OUTPUT_DIR)
>   File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/FastTrips.py", line 176, in run_assignment
>     r = Assignment.assign_paths(output_dir, self)
>   File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Assignment.py", line 642, in assign_paths
>     num_new_paths_found = Assignment.generate_pathsets(FT, pathset_paths_df, veh_trips_df, output_dir, iteration, pathfinding_iteration)
>   File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Assignment.py", line 862, in generate_pathsets
>     trace=do_trace)
>   File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Assignment.py", line 1016, in find_trip_based_pathset
>     1 if trace else 0)
> ValueError: need more than 12 values to unpack

**Comment by e-lo** [comment]
This is happening for each trace now - not sure what the dealio is.

**Comment by lmz** [comment]
Have you rebuilt?  I updated the cpp for the performance thing

**Comment by e-lo** [comment]
AHH
