### ISSUE TITLE
times for services spanning multiple dates

### ISSUE THREAD

**Issue by bhargavasana** [MetropolitanTransportationCommission/fast-trips#9]
According to GTFS, for services spanning multiple dates, the arrival/ departure times in stop_times.txt should be beyond 24:00:00 i.e., 25:05:000 or 26:35:00. However, datetime.datetime.strptime() does not like anything beyond "23:59:59". How should this be handled in fast-trips?

**Comment by lmz** [comment]
oh hmm... thanks for pointing that out.  I could do special date parsing i suppose.

**Comment by bhargavasana** [comment]
I tested the following function and it seems to be working:

    @staticmethod
    def convert_time(x):
        time_split = x.split(':')
        hour = int(time_split[0])
        day = datetime.datetime.today()
        if hour >= 24: 
            time_split[0] = '%02d' %(hour-24)
            day += datetime.timedelta(days=1)
        x = ':'.join(time_split)
        return datetime.datetime.combine(day, datetime.datetime.strptime(x, '%H:%M:%S').time())

**Comment by lmz** [comment]
Thanks to @bhargavasana for fixing this.
It's in develop and hyperpath_tree: https://github.com/MetropolitanTransportationCommission/fast-trips/commit/555a90d111af1d8ec8f6bf8256c1243a64dee1ae
